"""Updated column in User model

Revision ID: ee9ebee9dd7c
Revises: 
Create Date: 2025-06-20 21:34:35.918634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee9ebee9dd7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_participant')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('user_name')

    op.drop_table('user')
    op.drop_table('rating')
    op.drop_table('beer')
    op.drop_table('event')
    op.drop_table('event_beer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_beer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('beer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], name='event_beer_ibfk_3'),
    sa.ForeignKeyConstraint(['beer_id'], ['beer.id'], name='event_beer_ibfk_2'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_beer_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('beer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('brewery', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rating',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('beer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taste', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aftertaste', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('smell', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('design', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beer.id'], name='rating_ibfk_2'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='rating_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='rating_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('user_name', ['user_name'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('event_participant',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_participant_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='event_participant_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
