services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/app

  api:
    build: .
    command: python app.py --reload
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data:
