version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: beer_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/app

  web:
    build: .
    command: flask run --host=0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DB: beer_db
    depends_on:
      - db

volumes:
  mysql_data:
